function Hd = mybandpass
%MYBANDPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.3 and DSP System Toolbox 9.5.
% Generated on: 13-Nov-2020 23:45:03

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 400000;  % Sampling Frequency

Fstop1 = 5000;        % First Stopband Frequency
Fpass1 = 9000;        % First Passband Frequency
Fpass2 = 11000;       % Second Passband Frequency
Fstop2 = 15000;       % Second Stopband Frequency
Astop1 = 50;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 60;          % Second Stopband Attenuation (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
